-- Add amenities columns to branch table
ALTER TABLE branch ADD COLUMN IF NOT EXISTS has_parking BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE branch ADD COLUMN IF NOT EXISTS has_bathrooms BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE branch ADD COLUMN IF NOT EXISTS has_showers BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE branch ADD COLUMN IF NOT EXISTS has_lockers BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE branch ADD COLUMN IF NOT EXISTS has_wifi BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE branch ADD COLUMN IF NOT EXISTS has_cafeteria BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE branch ADD COLUMN IF NOT EXISTS has_equipment_rental BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE branch ADD COLUMN IF NOT EXISTS amenities_description TEXT;
